### ISSUE TITLE
Move all repos to a LuteOrg GitHub org (parent issue, contains many sub-issues)

### ISSUE THREAD

**Issue by jzohrab** [LuteOrg/lute-v3#346]
Currently, Lute and the Lute manual are in my personal GitHub account.

For sanity and the idea of "community ownership", this should be moved to a separate org.

This is similar to Anki, which has the org Ankitects (pretty sharp name -- after wasting way too much time trying to think of a name, the boring but totally fine name "LuteOrg" seems good enough. :-) )

To be included in the org:

* Lute
* the lute manual
* the epub parsing library that was written for Lute
* Lute Lemma (even though that's deprecated)

### Initial test:

- [x] create LuteOrg
- [x] #383
- [x] try transfer of dummy repo to org: see if issue links are copied correctly, stars copied correctly, see if cloned user can fetch from repo, check links in #383 
- [x] #384

### Transfer Lute manual

- [x] Commit all assets (images, gifs?) used by the manual to the manual's repo, in `/assets` directory.  Ref https://github.com/jzohrab/lute-manual/issues/9
- [x] Ensure local repo and gh pages repo has correct images when built
- [x] Reclone my fork to lute-manual-redirect (so I don't screw it up)
- [x] Create new lute-manual repo in LuteOrg
- [x] Change local remote to new repo
- [x] Push the current repo commits to LuteOrg, get the LuteOrg repo building and deploying to GH Pages
- [x] update book.toml in luteorg repo
- [x] fix any jzohrab/lute-manual links in LuteOrg
- [x] In jzohrab/lute-manual, remove all pages, put in redirection code, update README.  ref https://github.com/jzohrab/test-transfer-manual for pages, fix the javascript
- [x] Launch pages with redirection stuff, test it out, ensure redirections work, let it bake for a while
- [x] Archive the jzohrab/lute-manual repo, ensure things still work
- [x] change any links in the code to point to the new manual
- [x] change all youtube video links to point to new manual

### Transfer Lute repos

- [x] transfer lute-v3 repo
- [x] update manual if needed
- [x] ensure CI jobs run
- [x] transfer issues from my repo to the new one (maybe will be handled when the repo moves, see initial test)
- [x] change current PyPi to point to the new org, current Docker to point to new org

**Comment by jzohrab** [comment]
Moved main repos (code and manual).  Moving PyPi and DockerHub things to separate issues.

**Comment by jzohrab** [comment]
Launched in 3.3.2.
